### ISSUE TITLE
Fix projects m2e.or.tests, m2e.perftests and m2e.model.edit.tests or remove them

### ISSUE THREAD

**Issue by HannesWell** [tesla/m2e-core-tests#124]
The projects `org.eclipse.m2e.model.edit.tests`, `org.eclipse.m2e.perftests` and `org.eclipse.m2e.pr.tests` seem to be abandoned.
Their configuration is outdated and invalid and when it is fixed the code of `org.eclipse.m2e.perftests` and `org.eclipse.m2e.pr.tests` does not compile and the tests in `org.eclipse.m2e.model.edit.tests` fail.
Especially `org.eclipse.m2e.pr.tests` refers to packages named org.eclipse.m2e.pr that I did not found in m2e-core. So I think this project is obsolete. 

Therefore I suggest to delete obsolete projects.

**Comment by himanshu007-creator** [comment]
Can i work on this issue? if yes then please assign me this issue😀

**Comment by akurtakov** [comment]
You have it. But you can also open PRs without issue being assigned to you.

**Comment by HannesWell** [comment]
Thanks for the patch and merging.
