### ISSUE TITLE
Add Hannes and Christoph to team

### ISSUE THREAD

**Issue by mickaelistria** [tesla/m2e-core-tests#148]
@fbricon Can you please add @HannesWell and @laeubi to https://github.com/orgs/tesla/teams/m2e/members ? Or would it be possible for this repo to directly use the eclipse-m2e team ( https://github.com/orgs/eclipse-m2e/teams/technology-m2e-committers ) ?

**Comment by HannesWell** [comment]
Thank you @fbricon, Christoph and I are now part of the team.
