### ISSUE TITLE
Move to m2e-core repo

### ISSUE THREAD

**Issue by mickaelistria** [tesla/m2e-core-tests#64]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=541525

**Comment by laeubi** [comment]
@mickaelistria any chance for this to happen or should we close this?

**Comment by HannesWell** [comment]
Probably @waynebeaton can assess the chances even better.

**Comment by mickaelistria** [comment]
> any chance for this to happen or should we close this?


I've lost hope, so feel free to close.
